### ISSUE TITLE
Error when importing data

### ISSUE THREAD

**Issue by gidich** [trailheadapps/ebikes-communities-lwc#3]
When following the instructions the line below:

sfdx force:org:create -s -f config/project-scratch-def.json -a ebikes

Causes the following error:

ERROR running force:data:tree:import:  No such column 'Description__c' on sobject of type Product_Family__c

**Comment by kmesic** [comment]
@gidich Did you do a force:source:push before running the force:data:tree:import command?

**Comment by muenzpraeger** [comment]
This looks like the permission set hasn't been applied.
